spring:
  application:
    name: SCar

  datasource:
    url: jdbc:mysql://scar-db-seoul.cx2uyo68kyx6.ap-northeast-2.rds.amazonaws.com:3306/scar?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username: admin
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  sql:
    init:
      mode: never


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  jackson:
    time-zone: Asia/Seoul
    serialization:
      write-dates-as-timestamps: false

server:
  port: 8080
  servlet:
    context-path: /api          # API 경로 프리픽스 설정 (CloudFront 라우팅용)

jwt:
  secret: ${JWT_SECRET}         # 운영 환경은 환경변수로 주입
  token-validity-in-seconds: 3600 # 1 hour
  cookie-secure: true # 운영 환경은 HTTPS이므로 true (필수)